export const BerandaService = {
    getBerandasData() {
        return [
            {
                id: 1,
                title: 'Kaukus Pemimpin MSG',
                image: '/demo/img/melanesia/1.png',
                description: 'Product Description',
                lang: 'ID',
                author: 'Sekretariat MSG',
                year: '2024',
                datetime: '2024-11-25 02:00',
                category: 'Melanesia',
                pdfile: '/demo/pdf/Melanesia/1-ID.pdf'
            },
            {
                id: 2,
                title: 'MSG Leaders Caucus',
                image: '/demo/img/melanesia/1.png',
                description: 'MSG Description',
                lang: 'EN',
                author: 'MSG Secretariat',
                year: '2024',
                datetime: '2024-11-25 02:03',
                category: 'Melanesia',
                pdfile: '/demo/pdf/Melanesia/1-EN.pdf'
            },
            {
                id: 3,
                title: 'MSG Foreign Ministers Meeting',
                image: '/demo/img/melanesia/3.png',
                description: 'MSG Description',
                lang: 'EN',
                author: 'MSG Secretariat',
                year: '2024',
                datetime: '2024-11-25 02:06',
                category: 'Melanesia',
                pdfile: '/demo/pdf/Melanesia/2-EN.pdf'
            },
            {
                id: 4,
                title: 'Calendar Of Events 2025',
                image: '/demo/img/melanesia/4.png',
                description: 'MSG Description',
                lang: 'EN',
                author: 'MSG Secretariat',
                year: '2024',
                datetime: '2024-11-25 02:09',
                category: 'Melanesia',
                pdfile: '/demo/pdf/Melanesia/3-EN.pdf'
            },
            {
                id: 5,
                title: 'Babi Berpolitik',
                image: '/demo/img/unikab/1.png',
                description: 'Essay-Essay Menguak Pro – Kontra Pemekaran DOB di West Papua (Suatu Analogi)',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:12',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/1-ID.pdf'
            },
            {
                id: 6,
                title: 'Berburu Harta Karung di West Papua',
                image: '/demo/img/unikab/2.png',
                description: 'Berburu Harta Karung di West Papua',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:15',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/2-ID.pdf'
            },
            {
                id: 7,
                title: 'Buaya Darat Nama Naik',
                image: '/demo/img/unikab/3.png',
                description: 'Buaya Darat Nama Naik',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:18',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/3-ID.pdf'
            },
            {
                id: 8,
                title: 'Celana Umpan Panta Bensin',
                image: '/demo/img/unikab/4.png',
                description: 'Celana Umpan Panta Bensin',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:21',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/4-ID.pdf'
            },
            {
                id: 9,
                title: 'KTT G-20 & Perburuan Harta Karun di West Papua',
                image: '/demo/img/unikab/5.png',
                description: 'KTT G-20 & Perburuan Harta Karun di West Papua',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:24',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/5-ID.pdf'
            },
            {
                id: 10,
                title: 'Lola Lepu',
                image: '/demo/img/unikab/6.png',
                description: 'Lola Lepu',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:27',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/6-ID.pdf'
            },
            {
                id: 11,
                title: 'Makan Uang Darah',
                image: '/demo/img/unikab/7.png',
                description: 'Makan Uang',
                lang: 'ID',
                author: 'Russel Black',
                year: '2023',
                datetime: '2024-11-25 02:30',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/7-ID.pdf'
            },
            {
                id: 12,
                title: 'Musafir dan Kritikus',
                image: '/demo/img/unikab/8.png',
                description: 'Musafir dan Kritikus',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:33',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/8-ID.pdf'
            },
            {
                id: 13,
                title: 'Pace Mace Tajam',
                image: '/demo/img/unikab/9.png',
                description: 'Pace Mace Tajam',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:36',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/9-ID.pdf'
            },
            {
                id: 14,
                title: 'Pagar Makan Tanaman',
                image: '/demo/img/unikab/10.png',
                description: 'Pagar Makan Tanaman',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:39',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/10-ID.pdf'
            },
            {
                id: 15,
                title: 'Paha Putih Kode Alam',
                image: '/demo/img/unikab/11.png',
                description: 'Paha Putih Kode Alam',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:42',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/11-ID.pdf'
            },
            {
                id: 16,
                title: 'Pemekaran Mengancam Eksistensi OAP',
                image: '/demo/img/unikab/12.png',
                description: 'Pemekaran Mengancam Eksistensi OAP',
                lang: 'ID',
                author: 'Russel Black',
                year: '2017',
                datetime: '2024-11-25 02:45',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/12-ID.pdf'
            },
            {
                id: 17,
                title: 'Apa Pentingnya West Papua di MSG?',
                image: '/demo/img/unikab/13.png',
                description: 'Apa Pentingnya West Papua di MSG?',
                lang: 'ID',
                author: 'Unikab',
                year: '2023',
                datetime: '2024-11-25 02:48',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/13-ID.pdf'
            },
            {
                id: 18,
                title: 'Politik Gorengan',
                image: '/demo/img/unikab/14.png',
                description: 'Politik Gorengan',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:51',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/14-ID.pdf'
            },
            {
                id: 19,
                title: 'Pucuk Naik Daun',
                image: '/demo/img/unikab/15.png',
                description: 'Pucuk Naik Daun',
                lang: 'ID',
                author: 'Russel Black',
                year: '2022',
                datetime: '2024-11-25 02:54',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/15-ID.pdf'
            },
            {
                id: 20,
                title: 'Rakyat Bangsa Papua Berhak Menentukan Sikap',
                image: '/demo/img/unikab/16.png',
                description: 'RAKYAT BANGSA PAPUA BERHAK MENENTUKAN SIKAP',
                lang: 'ID',
                author: 'CHRIS DOGOPIA',
                year: '2022',
                datetime: '2024-11-25 02:57',
                category: 'UNIKAB',
                pdfile: '/demo/pdf/Unikab/16-ID.pdf'
            },
            {
                id: 21,
                title: 'West Papua And The Right To Self-Determination Under International Law',
                image: '/demo/img/westpapua/1.png',
                description: 'WEST PAPUA AND THE RIGHT TO SELF-DETERMINATION UNDER INTERNATIONAL LAW',
                lang: 'EN',
                author: 'Melinda Janki',
                year: '2010',
                datetime: '2024-11-25 03:00',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/1-EN.pdf'
            },
            {
                id: 22,
                title: 'Paying For Protection The Freeport mine and the Indonesian security forces',
                image: '/demo/img/westpapua/2.png',
                description: 'PAYING FOR PROTECTION The Freeport mine and the Indonesian security forces',
                lang: 'EN',
                author: 'Global Witness',
                year: '2005',
                datetime: '2024-11-25 03:03',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/2-EN.pdf'
            },
            {
                id: 23,
                title: 'West Papua 1942 to 2022 the legals, the politics, and the only way forward',
                image: '/demo/img/westpapua/3.png',
                description: 'WEST PAPUA 1942 to 2022 the legals, the politics, and the only way forward',
                lang: 'EN',
                author: 'Jacob Rumbiak',
                year: '2022',
                datetime: '2024-11-25 03:06',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/3-EN.pdf'
            },
            {
                id: 24,
                title: 'West Papua Real-Politic vs International Law (Summary)',
                image: '/demo/img/westpapua/4.png',
                description: 'WEST PAPUA Real-Politic vs International Law (Summary)',
                lang: 'EN',
                author: 'GE Lambert',
                year: '2000',
                datetime: '2024-11-25 03:09',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/4-EN.pdf'
            },
            {
                id: 25,
                title: 'Solving The Political Problem Of West Papua By Peaceful Means',
                image: '/demo/img/westpapua/5.png',
                description: 'Solving The Political Problem Of West Papua By Peaceful Means',
                lang: 'EN',
                author: 'Jacob Rumbiak',
                year: '2005',
                datetime: '2024-11-25 03:12',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/5-EN.pdf'
            },
            {
                id: 26,
                title: 'The Neglected Genocide',
                image: '/demo/img/westpapua/6.png',
                description: 'The Neglected Genocide',
                lang: 'EN',
                author: 'Asian Human Rights Commission',
                year: '2013',
                datetime: '2024-11-25 03:15',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/6-EN.pdf'
            },
            {
                id: 27,
                title: 'The Third Papuan Congress',
                image: '/demo/img/westpapua/7.png',
                description: 'The Third Papuan Congress',
                lang: 'EN',
                author: 'Unknown',
                year: '2011',
                datetime: '2024-11-25 03:18',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/7-EN.pdf'
            },
            {
                id: 28,
                title: 'West Papua Situation Update: March 2023',
                image: '/demo/img/westpapua/8.png',
                description: 'West Papua Situation Update: March 2023',
                lang: 'EN',
                author: 'ULMWP',
                year: '2023',
                datetime: '2024-11-25 03:21',
                category: 'ULMWP',
                pdfile: '/demo/pdf/WestPapua/8-EN.pdf'
            },
            {
                id: 29,
                title: 'Anglican Support for West Papua with Border',
                image: '/demo/img/westpapua/9.png',
                description: 'Anglican Support for West Papua with Border',
                lang: 'EN',
                author: 'WP Women Office',
                year: '2023',
                datetime: '2024-11-25 03:24',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/9-EN.pdf'
            },
            {
                id: 30,
                title: 'Is West Papua Another Timor?',
                image: '/demo/img/westpapua/10.png',
                description: 'Is West Papua Another Timor?',
                lang: 'EN',
                author: 'Dr J. R. Verrier',
                year: '2000',
                datetime: '2024-11-25 03:27',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/10-EN.pdf'
            },
            {
                id: 31,
                title: 'West Papua, Dag Hammarskjöld And The United Nations',
                image: '/demo/img/westpapua/11.png',
                description: 'West Papua, Dag Hammarskjöld And The United Nations',
                lang: 'EN',
                author: 'WP Women Office',
                year: '2023',
                datetime: '2024-11-25 03:30',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/11-EN.pdf'
            },
            {
                id: 32,
                title: 'An analysis of the 1969 Act of Free Choice in West Papua',
                image: '/demo/img/westpapua/12.png',
                description: 'An analysis of the 1969 Act of Free Choice in West Papua',
                lang: 'EN',
                author: 'Thomas D. Musgrave',
                year: '2013',
                datetime: '2024-11-25 03:33',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/12-EN.pdf'
            },
            {
                id: 33,
                title: 'An Act of Free Choice: Summary',
                image: '/demo/img/westpapua/13.png',
                description: 'An Act of Free Choice: Summary',
                lang: 'EN',
                author: 'Pieter Drooglever',
                year: '2013',
                datetime: '2024-11-25 03:36',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/13-EN.pdf'
            },
            {
                id: 34,
                title: '5 Unsur Pokok Dalam UUDS NRWP Yang Patut Diketahui Publik',
                image: '/demo/img/westpapua/14.png',
                description: '5 Unsur Pokok Dalam UUDS NRWP Yang Patut Diketahui Publik',
                lang: 'ID',
                author: 'PNWP',
                year: '2022',
                datetime: '2024-11-25 03:39',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/14-ID.pdf'
            },
            {
                id: 35,
                title: 'A slow-motion genocide: Indonesian rule in West Papua',
                image: '/demo/img/westpapua/15.png',
                description: 'A slow-motion genocide: Indonesian rule in West Papua',
                lang: 'EN',
                author: 'Jim Elmslie',
                year: '2013',
                datetime: '2024-11-25 03:42',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/15-EN.pdf'
            },
            {
                id: 36,
                title: 'Colonialism and Cold Genocide: The Case of West Papua',
                image: '/demo/img/westpapua/16.png',
                description: 'Colonialism and Cold Genocide: The Case of West Papua',
                lang: 'EN',
                author: 'Kjell Anderson',
                year: '2015',
                datetime: '2024-11-25 03:45',
                category: 'West Papua',
                pdfile: '/demo/pdf/WestPapua/16-EN.pdf'
            },
            {
                id: 37,
                title: 'Pernyataan ILWP tentang hasil KTT MSG 2023',
                image: '/demo/img/westpapua/17.png',
                description: 'Pernyataan ILWP tentang hasil KTT MSG 2023',
                lang: 'ID',
                author: 'ILWP',
                year: '2023',
                datetime: '2024-11-25 03:48',
                category: 'ILWP',
                pdfile: '/demo/pdf/WestPapua/17-ID.pdf'
            },
            {
                id: 38,
                title: 'Deklarasi Brussels Tentang Papua Barat',
                image: '/demo/img/ipwp/1-ID.png',
                description: 'Deklarasi Brussels Tentang Papua Barat',
                lang: 'ID',
                author: 'IPWP',
                year: '2024',
                datetime: '2024-11-26 23:08',
                category: 'IPWP',
                pdfile: '/demo/pdf/IPWP/1-ID.pdf'
            },
            {
                id: 39,
                title: 'Transmigrasi Ke Papua Barat: Pernyataan IPWP',
                image: '/demo/img/ipwp/2-ID.png',
                description: 'Transmigrasi Ke Papua Barat: Pernyataan IPWP',
                lang: 'ID',
                author: 'IPWP',
                year: '2024',
                datetime: '2024-11-26 23:28',
                category: 'IPWP',
                pdfile: '/demo/pdf/IPWP/2-ID.pdf'
            },
            {
                id: 40,
                title: 'Grup Parlemen Semua Partai Papua Barat (APPG) Diadakan Di Parlemen Inggris',
                image: '/demo/img/ipwp/3-ID.png',
                description: 'Grup Parlemen Semua Partai Papua Barat (APPG) Diadakan Di Parlemen Inggris',
                lang: 'ID',
                author: 'IPWP',
                year: '2024',
                datetime: '2024-11-27 00:07',
                category: 'IPWP',
                pdfile: '/demo/pdf/IPWP/3-ID.pdf'
            },
            {
                id: 41,
                title: 'Pertemuan IPWP Mendesak Kunjungan PBB Yang Mendesak Ke Papua Barat',
                image: '/demo/img/ipwp/4-ID.png',
                description: 'Pertemuan IPWP Mendesak Kunjungan PBB Yang Mendesak Ke Papua Barat',
                lang: 'ID',
                author: 'IPWP',
                year: '2023',
                datetime: '2024-11-27 00:29',
                category: 'IPWP',
                pdfile: '/demo/pdf/IPWP/4-ID.pdf'
            },
            {
                id: 42,
                title: 'Jaringan Dukungan Baru Untuk Papua Barat Diluncurkan Di Parlemen Eropa',
                image: '/demo/img/ipwp/5-ID.png',
                description: 'Jaringan Dukungan Baru Untuk Papua Barat Diluncurkan Di Parlemen Eropa',
                lang: 'ID',
                author: 'IPWP',
                year: '2022',
                datetime: '2024-11-27 00:58',
                category: 'IPWP',
                pdfile: '/demo/pdf/IPWP/5-ID.pdf'
            },
            {
                id: 43,
                title: 'Political prisoners must be released, not sentenced next week',
                image: '/demo/img/ilwp/1-EN.png',
                description: 'Political prisoners must be released, not sentenced next week',
                lang: 'EN',
                author: 'ILWP',
                year: '2020',
                datetime: '2024-11-29 02:13',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/1-EN.pdf'
            },
            {
                id: 44,
                title: 'ILWP Statement regarding ULMWP’s announcement of a provisional government',
                image: '/demo/img/ilwp/2-EN.png',
                description: 'ILWP Statement regarding ULMWP’s announcement of a provisional government',
                lang: 'EN',
                author: 'ILWP',
                year: '2020',
                datetime: '2024-11-29 02:17',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/2-EN.pdf'
            },
            {
                id: 45,
                title: 'Statement on Indonesia’s Crackdown in West Papua',
                image: '/demo/img/ilwp/3-EN.png',
                description: 'Statement on Indonesia’s Crackdown in West Papua',
                lang: 'EN',
                author: 'ILWP',
                year: '2021',
                datetime: '2024-11-29 02:21',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/3-EN.pdf'
            },
            {
                id: 46,
                title: 'Statement on Victor Yeimo',
                image: '/demo/img/ilwp/4-EN.png',
                description: 'Statement on Victor Yeimo',
                lang: 'EN',
                author: 'ILWP',
                year: '2021',
                datetime: '2024-11-29 02:24',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/4-EN.pdf'
            },
            {
                id: 47,
                title: 'Statement of Support for the Green State Vision',
                image: '/demo/img/ilwp/5-EN.png',
                description: 'Statement of Support for the Green State Vision',
                lang: 'EN',
                author: 'ILWP',
                year: '2021',
                datetime: '2024-11-29 02:26',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/5-EN.pdf'
            },
            {
                id: 48,
                title: 'Statement on 1 December student arrests',
                image: '/demo/img/ilwp/6-EN.png',
                description: 'Statement on 1 December student arrests',
                lang: 'EN',
                author: 'ILWP',
                year: '2021',
                datetime: '2024-11-29 02:30',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/6-EN.pdf'
            },
            {
                id: 49,
                title: 'Statement on EU - Indonesia Relations',
                image: '/demo/img/ilwp/7-EN.png',
                description: 'Statement on EU - Indonesia Relations',
                lang: 'EN',
                author: 'ILWP',
                year: '2022',
                datetime: '2024-11-29 02:33',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/7-EN.pdf'
            },
            {
                id: 50,
                title: 'ILWP UPR Submission Indonesia – November 2022',
                image: '/demo/img/ilwp/8-EN.png',
                description: 'ILWP UPR Submission Indonesia – November 2022',
                lang: 'EN',
                author: 'ILWP',
                year: '2022',
                datetime: '2024-11-29 02:37',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/8-EN.pdf'
            },
            {
                id: 50,
                title: 'Statement on ULMWP arrests',
                image: '/demo/img/ilwp/9-EN.png',
                description: 'Statement on ULMWP arrests',
                lang: 'EN',
                author: 'ILWP',
                year: '2022',
                datetime: '2024-11-29 02:40',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/9-EN.pdf'
            },
            {
                id: 51,
                title: 'Submission to the Special Rapporteur in the field of Cultural Rights',
                image: '/demo/img/ilwp/10-EN.png',
                description: 'Submission to the Special Rapporteur in the field of Cultural Rights',
                lang: 'EN',
                author: 'ILWP',
                year: '2023',
                datetime: '2024-11-29 02:44',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/10-EN.pdf'
            },
            {
                id: 52,
                title: 'ILWP Statement on 2023 MSG Summit outcome',
                image: '/demo/img/ilwp/11-EN.png',
                description: 'ILWP Statement on 2023 MSG Summit outcome',
                lang: 'EN',
                author: 'ILWP',
                year: '2023',
                datetime: '2024-11-29 02:48',
                category: 'ILWP',
                pdfile: '/demo/pdf/ILWP/11-EN.pdf'
            },
            {
                id: 53,
                title: 'Memahami Paripurna Legislative Council 2025',
                image: '/demo/img/dikpol/1-ID.jpg',
                description: 'Hasil Rapat Paripurna Legislative Council 2025',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-05 16:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/1-ID.pdf'
            },
            {
                id: 54,
                title: '13 Point Penting Resolusi Paripurna 2025',
                image: '/demo/img/dikpol/2-ID.jpg',
                description: '13 Point Penting Resolusi Paripurna 2025',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-05 17:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/2-ID.pdf'
            },
            {
                id: 55,
                title: 'Memahami Struktur di UN',
                image: '/demo/img/dikpol/3-ID.jpg',
                description: '13 Point Penting Resolusi Paripurna 2025',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-12 18:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/3-ID.pdf'
            },
            {
                id: 56,
                title: 'Memahami Hierarki (Urutan) Di Dalam Konstitusi 2020 Kita ',
                image: '/demo/img/dikpol/4-ID.jpg',
                description: 'Memahami Hierarki (Urutan) Di Dalam Konstitusi 2020 Kita',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-13 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/4-ID.pdf'
            },
            {
                id: 57,
                title: 'BAB XVII - Kekayaan',
                image: '/demo/img/dikpol/5-ID.jpg',
                description: 'Memahami BAB XVII tentang Kekayaan',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-14 19:48',
                category: 'UUDS',
                pdfile: '/demo/pdf/DIKPOL/5-ID.pdf'
            },
            {
                id: 58,
                title: 'BAB XV - Pengambilan Keputusan',
                image: '/demo/img/dikpol/6-ID.jpg',
                description: 'Memahami BAB XV tentang Pengambilan Keputusan',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-15 19:48',
                category: 'UUDS',
                pdfile: '/demo/pdf/DIKPOL/6-ID.pdf'
            },
            {
                id: 59,
                title: 'BAB VII - Legislative Council',
                image: '/demo/img/dikpol/7-ID.jpg',
                description: 'Memahami BAB VII tentang Legislative Council',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-16 19:48',
                category: 'UUDS',
                pdfile: '/demo/pdf/DIKPOL/7-ID.pdf'
            },
            {
                id: 60,
                title: 'Data Suku di Wilayah Bomberay',
                image: '/demo/img/bomberay/1-ID.jpg',
                description: 'Memahami BAB VI tentang Legislative Council',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2025',
                datetime: '2025-07-16 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/1-ID.pdf'
            },
            {
                id: 61,
                title: 'Peta Administrasi Bomberay',
                image: '/demo/img/bomberay/2-ID.jpg',
                description: 'Peta Administrasi Bomberay',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2025',
                datetime: '2025-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/2-ID.pdf'
            },
            {
                id: 62,
                title: 'Data Suku di Bomberay, Saireri, Douberay',
                image: '/demo/img/bomberay/3-ID.png',
                description: 'Peta Administrasi Bomberay',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2025',
                datetime: '2025-07-18 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/3-ID.pdf'
            },
            {
                id: 63,
                title: 'Menteri & Kementrian Yang Di Umumkan Tn. Presiden',
                image: '/demo/img/ulmwp/2-ID.png',
                description: 'Peta Administrasi Bomberay',
                lang: 'ID',
                author: 'ULMWP',
                year: '2021',
                datetime: '2021-07-19 19:48',
                category: 'ULMWP',
                pdfile: '/demo/pdf/ULMWP/2-ID.pdf'
            },
            {
                id: 64,
                title: 'Daftar Negara di OACP (Negara-Negara Kulit Hitam)',
                image: '/demo/img/dikpol/8-ID.jpg',
                description: 'Daftar Negara di OACP',
                lang: 'ID',
                author: 'JJ',
                year: '2019',
                datetime: '2019-07-16 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/8-ID.pdf'
            },
            {
                id: 65,
                title: 'Saralana Declaration (Deklarasi Saralana)',
                image: '/demo/img/ulmwp/3-EN.png',
                description: 'Peta Administrasi Bomberay',
                lang: 'EN',
                author: 'ULMWP',
                year: '2014',
                datetime: '2014-07-19 19:48',
                category: 'ULMWP',
                pdfile: '/demo/pdf/ULMWP/3-EN.pdf'
            },
            {
                id: 66,
                title: 'Materi Sosialisasi Tentang "Apa Itu Pemerintah Sementara ?"',
                image: '/demo/img/dikpol/9-ID.jpg',
                description: 'Materi Sosialisasi Tentang "Apa Itu Pemerintah Sementara ?"',
                lang: 'ID',
                author: 'JJ',
                year: '2024',
                datetime: '2024-05-16 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/9-ID.pdf'
            },
            {
                id: 67,
                title: 'Format Buku A4 UUDS 2020',
                image: '/demo/img/dikpol/10-ID.jpg',
                description: 'Format Buku A4 UUDS 2020',
                lang: 'ID',
                author: 'JJ',
                year: '2021',
                datetime: '2021-05-15 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/10-ID.pdf'
            },
            {
                id: 68,
                title: 'Sosialisasi "Apa Pentingnya West Papua di MSG?"',
                image: '/demo/img/dikpol/11-ID.jpg',
                description: 'Sosialisasi "Apa Pentingnya West Papua di MSG?"',
                lang: 'ID',
                author: 'JJ',
                year: '2023',
                datetime: '2023-05-12 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/11-ID.pdf'
            },
            {
                id: 69,
                title: 'Sosialisasi "Persiapan Konferensi Wilayah Bomberay"',
                image: '/demo/img/dikpol/12-ID.png',
                description: 'Konferensi Wilayah Bomberay',
                lang: 'ID',
                author: 'JJ',
                year: '2024',
                datetime: '2024-03-12 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/12-ID.pdf'
            },
            {
                id: 70,
                title: 'Green State Vision',
                image: '/demo/img/gsv/1-EN.jpg',
                description: 'GSV',
                lang: 'EN',
                author: 'GSV Team',
                year: '2021',
                datetime: '2021-03-12 19:48',
                category: 'GSV',
                pdfile: '/demo/pdf/GSV/1-EN.pdf'
            },
            {
                id: 71,
                title: 'Vision of Better World (GSV Hal 49-61)',
                image: '/demo/img/gsv/2-EN.jpg',
                description: 'GSV',
                lang: 'EN',
                author: 'GSV Team',
                year: '2023',
                datetime: '2023-03-12 19:48',
                category: 'GSV',
                pdfile: '/demo/pdf/GSV/2-EN.pdf'
            },
            {
                id: 72,
                title: 'Institusional Gov Structure (Struktur Pemerintah)',
                image: '/demo/img/ulmwp/4-EN.png',
                description: 'Institusional Gov Structure',
                lang: 'EN',
                author: 'ULMWP',
                year: '2021',
                datetime: '2021-03-12 19:48',
                category: 'ULMWP',
                pdfile: '/demo/pdf/ULMWP/4-EN.pdf'
            },
            {
                id: 73,
                title: 'Temporary Constitution (Konstitusi Sementara)',
                image: '/demo/img/ulmwp/5-ID.png',
                description: 'Temporary Constitution (Konstitusi Sementara)',
                lang: 'ID',
                author: 'ULMWP',
                year: '2020',
                datetime: '2020-03-12 19:48',
                category: 'ULMWP',
                pdfile: '/demo/pdf/ULMWP/5-ID.pdf'
            },
            {
                id: 74,
                title: 'Proses Untuk Menjadi Anggota PBB',
                image: '/demo/img/dikpol/13-ID.jpg',
                description: 'Proses Untuk Menjadi Anggota PBB',
                lang: 'ID',
                author: 'JJ',
                year: '2020',
                datetime: '2020-03-12 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/13-ID.pdf'
            },
            {
                id: 75,
                title: 'Analisis Geopolitk Pasca Kongres 2023',
                image: '/demo/img/dikpol/14-ID.jpg',
                description: 'Analisis Geopolitk Pasca Kongres 2023',
                lang: 'ID',
                author: 'JJ',
                year: '2023',
                datetime: '2023-12-20 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/14-ID.pdf'
            },
            {
                id: 76,
                title: 'Peta Administrasi Kaimana',
                image: '/demo/img/bomberay/4-ID.jpg',
                description: 'Peta Administrasi Kaimana',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2023',
                datetime: '2023-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/4-ID.pdf'
            },
            {
                id: 77,
                title: 'Peta Administrasi Fak-Fak',
                image: '/demo/img/bomberay/5-ID.jpg',
                description: 'Peta Administrasi Fak-Fak',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2023',
                datetime: '2023-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/5-ID.pdf'
            },
            {
                id: 78,
                title: 'Peta Administrasi Bintuni',
                image: '/demo/img/bomberay/6-ID.jpg',
                description: 'Peta Administrasi Bintuni',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2023',
                datetime: '2023-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/6-ID.pdf'
            },
            {
                id: 79,
                title: 'Peta Administrasi Mimika Pantai dan Mimika Kota',
                image: '/demo/img/bomberay/7-ID.jpg',
                description: 'Peta Administrasi Mimika Pantai dan Mimika Kota',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2023',
                datetime: '2023-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/7-ID.pdf'
            },
            {
                id: 80,
                title: 'Struktur di OACP',
                image: '/demo/img/dikpol/15-ID.jpg',
                description: 'Struktur di OACP',
                lang: 'ID',
                author: 'JJ',
                year: '2020',
                datetime: '2020-12-20 19:48',
                category: 'DIKPOL',
                pdfile: '/demo/pdf/DIKPOL/15-ID.pdf'
            },
            {
                id: 81,
                title: 'SK Pengangkatan & Penetapan Kepala Wilayah Pemerintahan',
                image: '/demo/img/ulmwp/6-ID.png',
                description: 'SK Pengangkatan & Penetapan Kepala Wilayah Pemerintahan',
                lang: 'ID',
                author: 'ULMWP',
                year: '2022',
                datetime: '2022-03-12 19:48',
                category: 'ULMWP',
                pdfile: '/demo/pdf/ULMWP/6-ID.pdf'
            },
            {
                id: 82,
                title: 'Daftar Administrasi Distrik di Bomberay',
                image: '/demo/img/bomberay/8-ID.jpg',
                description: 'Daftar Administrasi Distrik di Bomberay',
                lang: 'ID',
                author: 'Sekretariat Bomberay',
                year: '2024',
                datetime: '2024-07-17 19:48',
                category: 'BOMBERAY',
                pdfile: '/demo/pdf/BOMBERAY/8-ID.pdf'
            },
            {
                id: 83,
                title: 'BAB VI - Badan Pertahanan & Keamanan',
                image: '/demo/img/dikpol/16-ID.jpg',
                description: 'Memahami BAB VI tentang Badan Pertahanan & Keamanan',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-18 19:48',
                category: 'UUDS',
                pdfile: '/demo/pdf/DIKPOL/16-ID.pdf'
            },
            {
                id: 84,
                title: 'Daftar Partai Politik di Vanuatu',
                image: '/demo/img/melanesia/5-ID.jpg',
                description: 'Daftar Partai Politik di Vanuatu',
                lang: 'ID',
                author: 'JJ',
                year: '2018',
                datetime: '2018-07-18 19:48',
                category: 'Melanesia',
                pdfile: '/demo/pdf/Melanesia/5-ID.pdf'
            },
            {
                id: 85,
                title: 'BAB II - Kongres',
                image: '/demo/img/dikpol/17-ID.jpg',
                description: 'Memahami BAB II tentang Kongres',
                lang: 'ID',
                author: 'JJ',
                year: '2025',
                datetime: '2025-07-18 19:48',
                category: 'UUDS',
                pdfile: '/demo/pdf/DIKPOL/17-ID.pdf'
            }
        ];
    },

    getBerandasMini() {
        return Promise.resolve(this.getBerandasData().slice(0, 5));
    },

    getBerandasSmall() {
        return Promise.resolve(this.getBerandasData().slice(0, 10));
    },

    getBerandas() {
        return Promise.resolve(this.getBerandasData());
    },

    getBerandasWithOrdersSmall() {
        return Promise.resolve(this.getBerandasWithOrdersData().slice(0, 10));
    },

    getBerandasWithOrders() {
        return Promise.resolve(this.getBerandasWithOrdersData());
    }
};
